ENG-962 Instructions on getting set up with gitpod.io
uberflip/interview-eng-i pull request #2
Opened 2021-11-12 14:41 UTC by agbasioscar

Decide on workflow (Forking?) How do we view their gitpod environment?

Deliverables:

* Documentation on how to get coding/begin the evaluation on gitpod.io

2021-11-19 16:15 UTC, guil-uberflip commented
Approved

2021-12-02 19:52 UTC, robmontebelli reviewed
We now have 2 mockup files (one png that's 11 MB and should be smaller) and I'm not sure what the png file refers to

2021-12-02 19:52 UTC, robmontebelli commented on README.md
> +Make sure the names and description of the exact instead of {name} or {description}
Is there a typo here? Also, I am not sure what the response and description are 🤔

2021-12-02 19:52 UTC, robmontebelli commented on README.md
> +### 5. Toggle functionality
Which toggle is it referring to?

2021-12-14 17:49 UTC, jrisebor requested changes

2021-12-14 17:49 UTC, jrisebor commented on README.md
>  While waiting for the results from the image API to be returned and rendered, display a loading indicator. A spinner image can be found under the `public` directory. The spinner should be displayed a
tasks 2 & 4 here also seem like frontend tasks (I guess 4 is a bit of both), should they be under the frontend heading? Also I think the numbering needs to be corrected as well.

2021-12-14 17:49 UTC, jrisebor commented on README.md
> +#### 1. Move your mouse over the workspace you want to share (change the filter to All if you don’t see your workspace.
Should this be H3 instead of H4? (i.e. `###` instead of `####`?)

2022-01-05 19:38 UTC, merged